const DESCRIPTIONS = {
  alliances: "Show alliances/allies for a turn.",
  allmuplinks: "Show all MUP links.",
  muplinkexport: "Export all MUP links to a text file. (Aliases: MupLinksExport, MupLinksTXT)",
  allmups: "Show all MUP images.",
  bonuses: "Show all current player bonuses.",
  cedes: "Show cedes for a turn.",
  exportgame: "Export/game export to a text file. (Aliases: GameExport)",
  help: "Show bot help, rules, or help for a command. (Aliases: H)",
  helplevel: "Show XP, profiles, and leaderboard help. (Aliases: HLevel, HL)",
  helpmaster: "Show game master help. (Aliases: HMaster, HM)",
  helpplayer: "Show player help. (Aliases: HPlayer, HP)",
  helputil: "Show utility command help. (Aliases: HUtil, HU)",
  history: "Show history/events for a turn. (Aliases: E)",
  historybonus: "Show history/events with current player bonuses. (Aliases: EventsBonus, EB)",
  links: "Show roll message links for a turn. (Aliases: L)",
  notes: "Show player notes for a turn. (Aliases: N)",
  gameid: "Open a current or previous game by id.",
  pacts: "Show pacts/NAPs for a turn.",
  profile: "Player: Show your profile's level card. (Aliases: Rank)",
  rolls: "Show roll history for a turn. (Aliases: Rs)",
  status: "Show the current game status.",
  s: "Show a compact game status.",
  g: "Show a compact game status.",
  who: "Show who is left to roll. (Aliases: W)",

  announce: "Master: Announce/add a message to game history. (Aliases: Proclaim, An)",
  betrayallalliances: "Master: Break/betray all alliances. (Aliases: BetrayAllAllies)",
  breakallpacts: "Master: Break all pacts/NAPs. (Aliases: BreakAllNAPs)",
  close: "Master: Close or reopen player joins. (Aliases: CloseClaims, CloseJoins, ReopenClaims, ReopenJoins)",
  endgame: "Master: End/finish and archive the current game. (Aliases: FinishGame, Peace, EndMup)",
  renamegame: "Master: Rename/change the current game title. (Aliases: ChangeTitle)",
  reopengame: "Master: Reopen/restart the latest finished game in this channel. (Aliases: RestartGame)",
  startgame: "Master: Start, host, or create a new game in this channel. (Aliases: NewGame)",
  transfergame: "Master: Transfer game master control.",
  lurkeradd: "Master: Add lurkers to the game. (Aliases: AddLurker)",
  add: "Master: Add/change players.",
  forceally: "Master: Force an alliance between two players. (Aliases: ForceAlliance)",
  ban: "Master: Purge a player from the game.",
  baninactive: "Master: Ban/purge players no longer in the server. (Aliases: PurgeInactive)",
  forcebetray: "Master: Force-break an alliance between two players.",
  setbonus: "Master: Set player bonuses. (Aliases: B)",
  forcebreak: "Master: Force-break a NAP between two players. (Aliases: ForceNAPBreak)",
  cleardiplomacy: "Master: Clear a player's alliances and NAPs.",
  kick: "Master: Remove a player on the next turn.",
  kill: "Master: Kill a player.",
  forcenap: "Master: Force a NAP/pact between two players. (Aliases: ForcePact)",
  ping: "Master: Ping players who have not rolled. (Aliases: NotPlayed)",
  pingalive: "Master: Ping all alive players.",
  pingeveryone: "Master: Ping all players.",
  revive: "Master: Revive a dead player.",
  setnote: "Master: Set player notes.",
  poll: "Master: Set or show this turn's poll/election. (Aliases: Decision)",
  forceroll: "Master: Force a roll for a player. (Aliases: SkipPlayer, frfr)",
  setmaxallies: "Master: Set or clear the ally limit. (Aliases: AllyLimit)",
  setmaxnaps: "Master: Set or clear the NAP limit. (Aliases: NAPLimit, NAPsLimit)",
  slot: "Master: Add claimable faction slots.",
  slotclear: "Master: Clear all faction slots. (Aliases: SClear)",
  slotkeep: "Master: Keep or reset faction slots after turns. (Aliases: SKeep, KeepSlots, KeepSlot, SlotsKeep)",
  slotremove: "Master: Remove faction slots. (Aliases: SRemove)",
  turn: "Master: Post a new Mup for the next turn.",
  turnedit: "Master: Edit the current turn/MUP. (Aliases: MupEdit, EditMup)",
  editold: "Master: Edit an old turn.",

  ally: "Player: Ally with other players.",
  betray: "Player: Break alliances with other players.",
  cede: "Player: Cede/send land to another player.",
  checkneedroll: "Player: Check games where you still need to roll. (Aliases: CheckGames, iforgor)",
  claim: "Player: Join a game or rename your faction.",
  hardquit: "Player: Leave permanently and prevent master re-adds.",
  nap: "Player: Make NAPs with other players.",
  break: "Player: Break/wake from NAPs with other players.",
  ragequit: "Player: Ragequit/leave on the next turn. (Aliases: Resign)",
  say: "Player: Add a message to the game history.",
  skip: "Player: Mark yourself as rolled this turn.",
  vote: "Player: Vote in this turn's poll.",

  roll: "Player: Roll with an optional intention. (Aliases: R)",
  rolld: "Player: Roll with a custom limit. (Aliases: RD, D)",
  rolldx: "Player: Roll multiple times with a custom limit. (Aliases: RDX, DX)",
  rolldnd: "Player: Roll using DnD dice notation. (Aliases: RDnD)",
  rollid: "Player: Roll using Discord's message id. (Aliases: RID)",
  rollx: "Player: Roll multiple times. (Aliases: RX, X)",
  rollxd: "Player: Roll multiple times with a custom limit. (Aliases: RXD, XD)",
  testroll: "Player: Make an unsaved test roll. (Aliases: T)",
  testrolldice: "Player: Make an unsaved test roll with a custom limit. (Aliases: TestD, TD)",
  testrolldx: "Player: Make unsaved test rolls with a custom limit. (Aliases: TestDX, TDX)",
  testrolldnd: "Player: Make an unsaved DnD dice roll. (Aliases: TestDnD, TDnD)",
  testrollid: "Player: Make an unsaved test roll using Discord's message id. (Aliases: TestId, TID)",
  testrollx: "Player: Make multiple unsaved test rolls. (Aliases: TestX, TX)",
  testrollxd: "Player: Make multiple unsaved test rolls with a custom limit. (Aliases: TestXD, TXD)",
  reference: "Show how a roll value would be formatted. (Aliases: RefTest)",

  duel: "Master: Run a duel between two users.",
  games: "Browse current and previous games in this server. (Aliases: BrowseGames)",
  past: "Browse previous/old games.",
  pasthere: "Browse previous games in this channel.",
  pastplayer: "Browse previous games played by a user.",
  rollinitiative: "Master: Roll/list player initiative order.",
  top: "Player: Show player ranks/leaderboard.",
  hall: "Player: Show the roll leaderboard. (Aliases: TopR)",
  luck: "Show player luck in this game. (Aliases: GameLuck)",
  lurk: "Player: Become a lurker for this game.",
  unlurk: "Master: Remove a lurker, or remove yourself. (Aliases: RemoveLurker)",
}

function slashDescription(commandName, commandType) {
  const text = DESCRIPTIONS[commandName] || commandType.description || "Calculated Risk command."
  return text.replace(/\s+/g, " ").slice(0, 100) || "Calculated Risk command."
}

module.exports = {
  DESCRIPTIONS,
  slashDescription,
}
