const DESCRIPTIONS = {
  alliances: "Show alliances/allies for a turn.",
  allmuplinks: "Show all MUP links.",
  muplinkexport: "Export all MUP links to a text file.",
  allmups: "Show all MUP images.",
  bonuses: "Show all current player bonuses.",
  cedes: "Show cedes for a turn.",
  exportgame: "Export/game export to a text file.",
  help: "Show bot help, rules, or help for a command.",
  helplevel: "Show XP, profiles, and leaderboard help.",
  helpmaster: "Show game master help.",
  helpplayer: "Show player help.",
  helputil: "Show utility command help.",
  history: "Show history/events for a turn.",
  historybonus: "Show history/events with current player bonuses.",
  links: "Show roll message links for a turn.",
  notes: "Show player notes for a turn.",
  gameid: "Open a current or previous game by id.",
  pacts: "Show pacts/NAPs for a turn.",
  profile: "Player: Show your profile's level card.",
  rolls: "Show roll history for a turn.",
  status: "Show the current game status.",
  s: "Show a compact game status.",
  g: "Show a compact game status.",
  who: "Show who is left to roll.",

  announce: "Master: Announce/add a message to game history.",
  betrayallalliances: "Master: Break/betray all alliances.",
  breakallpacts: "Master: Break all pacts/NAPs.",
  close: "Master: Close or reopen player joins.",
  endgame: "Master: End/finish and archive the current game.",
  renamegame: "Master: Rename/change the current game title.",
  reopengame: "Master: Reopen/restart the latest finished game in this channel.",
  startgame: "Master: Start, host, or create a new game in this channel.",
  transfergame: "Master: Transfer game master control.",
  lurkeradd: "Master: Add lurkers to the game.",
  add: "Master: Add/change players.",
  forceally: "Master: Force an alliance between two players.",
  ban: "Master: Purge a player from the game.",
  baninactive: "Master: Ban/purge players no longer in the server.",
  forcebetray: "Master: Force-break an alliance between two players.",
  setbonus: "Master: Set player bonuses.",
  forcebreak: "Master: Force-break a NAP between two players.",
  cleardiplomacy: "Master: Clear a player's alliances and NAPs.",
  kick: "Master: Remove a player on the next turn.",
  kill: "Master: Kill a player.",
  forcenap: "Master: Force a NAP/pact between two players.",
  ping: "Master: Ping players who have not rolled.",
  pingalive: "Master: Ping all alive players.",
  pingeveryone: "Master: Ping all players.",
  revive: "Master: Revive a dead player.",
  setnote: "Master: Set player notes.",
  poll: "Master: Set or show this turn's poll/election.",
  forceroll: "Master: Force a roll for a player.",
  setmaxallies: "Master: Set or clear the ally limit.",
  setmaxnaps: "Master: Set or clear the NAP limit.",
  slot: "Master: Add claimable faction slots.",
  slotclear: "Master: Clear all faction slots.",
  slotkeep: "Master: Keep or reset faction slots after turns.",
  slotremove: "Master: Remove faction slots.",
  turn: "Master: Post a new Mup for the next turn.",
  turnedit: "Master: Edit the current turn/MUP.",
  editold: "Master: Edit an old turn.",

  ally: "Player: Ally with other players.",
  betray: "Player: Break alliances with other players.",
  cede: "Player: Cede/send land to another player.",
  checkneedroll: "Player: Check games where you still need to roll.",
  claim: "Player: Join a game or rename your faction.",
  hardquit: "Player: Leave permanently and prevent master re-adds.",
  nap: "Player: Make NAPs with other players.",
  break: "Player: Break/wake from NAPs with other players.",
  ragequit: "Player: Ragequit/leave on the next turn.",
  say: "Player: Add a message to the game history.",
  skip: "Player: Mark yourself as rolled this turn.",
  vote: "Player: Vote in this turn's poll.",

  roll: "Player: Roll with an optional intention.",
  rolld: "Player: Roll with a custom limit.",
  rolldx: "Player: Roll multiple times with a custom limit.",
  rolldnd: "Player: Roll using DnD dice notation.",
  rollid: "Player: Roll using Discord's message id.",
  rollx: "Player: Roll multiple times.",
  rollxd: "Player: Roll multiple times with a custom limit.",
  testroll: "Player: Make an unsaved test roll.",
  testrolldice: "Player: Make an unsaved test roll with a custom limit.",
  testrolldx: "Player: Make unsaved test rolls with a custom limit.",
  testrolldnd: "Player: Make an unsaved DnD dice roll.",
  testrollid: "Player: Make an unsaved test roll using Discord's message id.",
  testrollx: "Player: Make multiple unsaved test rolls.",
  testrollxd: "Player: Make multiple unsaved test rolls with a custom limit.",
  reference: "Show how a roll value would be formatted.",

  duel: "Master: Run a duel between two users.",
  games: "Browse current and previous games in this server.",
  past: "Browse previous/old games.",
  pasthere: "Browse previous games in this channel.",
  pastplayer: "Browse previous games played by a user.",
  rollinitiative: "Master: Roll/list player initiative order.",
  top: "Player: Show player ranks/leaderboard.",
  hall: "Player: Show the roll leaderboard.",
  luck: "Show player luck in this game.",
  lurk: "Player: Become a lurker for this game.",
  unlurk: "Master: Remove a lurker, or remove yourself.",
}

function slashDescription(commandName, commandType) {
  const text = DESCRIPTIONS[commandName] || commandType.description || "Calculated Risk command."
  return text.replace(/\s+/g, " ").slice(0, 100) || "Calculated Risk command."
}

module.exports = {
  DESCRIPTIONS,
  slashDescription,
}
